Use Ruby stdlib logger
PascalTurbo/feedjira pull request #1
Opened 2017-01-26 05:15 UTC by mikeastock

This allows us to not maintain our own custom logger as well as allow
users to swap out the logger with any object that conforms to the Ruby
logger API. Most of the work in this PR was pulled from examples on
Ruby's logger docs.

http://ruby-doc.org/stdlib-2.1.2/libdoc/logger/rdoc/Logger.html

2017-01-26 07:06 UTC, PascalTurbo commented
I've add a few comments.

Your solution is slimmer then mine - but wasn't really necessary to achieve your goal. In my implementation you could also replace the logger - maybe I forgot to add this to documentation.

2017-01-26 07:06 UTC, PascalTurbo requested changes

2017-01-26 07:06 UTC, PascalTurbo commented on lib/feedjira/core_ext/time.rb
I don't like the idea replacing the block with a method call. This is OK if you are only processing a few feeds. In my usecase there are so  many calls of this method, that evaluating the String every call will result in a loss of performance.

Indeed, this isn't really necessary because Logger.fatal also supports a block.

2017-01-26 07:06 UTC, PascalTurbo commented on lib/feedjira/feed.rb
>      end
Here you changed the behavior of the Logging. The first message should be a warning, the second the fatal message.

2017-01-26 07:06 UTC, PascalTurbo commented on lib/feedjira/configuration.rb
> +        logger.level = Logger::WARN
Good solution - I haven't found to set the"default progname"

2017-01-26 07:06 UTC, PascalTurbo commented on lib/feedjira/feed.rb
>          nil
I just don't have a ruby environment here. Will Logger.fatel(e) also format the exeption and spill out the StackTrace?

2017-01-27 04:36 UTC, mikeastock commented on lib/feedjira/feed.rb
>          nil
No I don't believe so however I don't of many gems besides Rails that do this.

2017-01-27 04:36 UTC, mikeastock commented on lib/feedjira/core_ext/time.rb
Do you feel like the string interpolation is a performance problem?

2017-01-27 07:49 UTC, PascalTurbo commented on lib/feedjira/core_ext/time.rb
It's not only a feeling - I've measured that in our app using feedjira. After implementing logging (with a lot of debug outputs) we've found higher CPU Usage than before - and after some investigation, we've replaced all the method calls with blocks - Problem solved.

2017-01-28 05:48 UTC, mikeastock commented
I don't know how I feel about using `warn` and `fatal` to log the same error. Do you think we should be consistent and use just one of the two?

2017-01-28 05:49 UTC, mikeastock commented on lib/feedjira/feed.rb
> +        Feedjira.logger.warn { "Failed to parse last modified '#{lm}'" }
This was the inconsistency I'm talking about

2017-01-28 05:49 UTC, mikeastock commented on lib/feedjira/feed.rb
> +        Feedjira.logger.warn { "Failed to parse last modified '#{lm}'" }
Why use warn and not fatal?

2017-01-31 15:50 UTC, mikeastock commented
I think this is ready

2017-02-01 07:42 UTC, PascalTurbo commented
I'll merge that whole thing and then change "fatal" back to "debug". You only need these Log messages for Debugging. Have a look at the ruby logger dokumentation:

FATAL: "An unhandleable error that results in a program crash."

I'll also have a look to log always the same type.

2017-02-01 07:42 UTC, merged

2017-02-01 07:48 UTC, PascalTurbo commented
I had to revert the pull request. There are rubocop errors

2017-02-01 07:53 UTC, PascalTurbo commented
After the third change on https://github.com/PascalTurbo/feedjira/pull/1 I'm a little unhappy about that quality.

So I would prefer merging my version.
One of the reasons I created an own Logger abstraction was to create a simple way for logging multiple types of Log Messages with a simple interface. This also prevents writing multiple lines of code for logging (Logger.exception replaces two logging lines). With the PR of mikeatock there came new rubocop warnings in. Also the log level is wrong (using fatal instead of debug).